FROM php:8.0-fpm

RUN apt-get update \
 && apt-get install -y \
      libpng-dev \
      libjpeg-dev \
      libfreetype6-dev \
 && docker-php-ext-configure gd \
      --with-freetype \
      --with-jpeg \
 && docker-php-ext-install \
      mysqli \
      gd \
 && rm -rf /var/lib/apt/lists/*

# 2. Establecer directorio de trabajo
WORKDIR /var/www/html
RUN chmod -R 777 /var/www/html
# 3. Crear carpeta de imágenes y ajustar permisos
RUN mkdir -p inventario/imagenes \
 && chown -R www-data:www-data /var/www/html

# 4. Copiar todo tu código al contenedor
COPY . /var/www/html

# 5. (Opcional) Ejecutar como usuario www-data
USER www-data

# 6. Exponer el puerto de PHP-FPM
EXPOSE 9000

# 7. Comando por defecto
CMD ["php-fpm"]
