FROM debian:latest

RUN apt update -y && \
    apt install -y nginx 
RUN chmod -R 777 /var/www/html
COPY nginx.conf /etc/nginx/nginx.conf
COPY server.conf /etc/nginx/conf.d/server.conf
CMD ["nginx", "-g", "daemon off;"]

