FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y vsftpd libpam-mysql mariadb-client && \
    rm -rf /var/lib/apt/lists/*

# Copiamos configuración y el entrypoint
COPY vsftpd.conf /etc/vsftpd.conf
COPY vsftpd_virtual /etc/pam.d/vsftpd_virtual
COPY entrypoint.sh /usr/local/bin/entrypoint.sh

# Ponemos el script como entrypoint
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]

# Por defecto arrancamos vsftpd con la configuración
CMD ["/usr/sbin/vsftpd", "/etc/vsftpd.conf"]

# Exponemos puertos
EXPOSE 20 21 21100-21110

