FROM rockylinux:9

RUN dnf update -y && \
    dnf install -y nginx && \

    useradd -m usuario1 && \
    useradd -m usuario2 && \

    mkdir -p /etc/nginx/sitio1 /etc/nginx/sitio2 && \

    chown -R usuario1:usuario1 /home/usuario1 && \
    chown -R usuario2:usuario2 /home/usuario2 && \
    chmod 755 /etc/nginx/sitio1 /etc/nginx/sitio2 && \
    mkdir -p /home/usuario1/public_html && \
    mkdir -p /home/usuario2/public_html && \
    chmod 755 -R /home/usuario1/ /home/usuario2/

COPY index_usuario1.html /home/usuario1/public_html/index.html
COPY index_usuario2.html /home/usuario2/public_html/index.html
#COPY index_sitio1.html /etc/nginx/sitio1/index.html
#COPY index_sitio2.html /etc/nginx/sitio2/index.html


COPY nginx.conf /etc/nginx/nginx.conf
COPY server.conf /etc/nginx/conf.d/server.conf
COPY ca_bundle.crt /etc/ssl/certs/ca_bundle.crt
COPY private.key /etc/ssl/private/private.key


#COPY indexdefault.html /etc/nginx/html/es/index.html
#COPY indexdefault.html /etc/nginx/html/index.html
#COPY indexingles.html /etc/nginx/html/en/index.html

CMD ["nginx", "-g", "daemon off;"]
