FROM osixia/openldap:1.5.0

# Copiar archivos de configuración
COPY bootstrap.ldif /tmp/bootstrap.ldif


# Configurar variables de entorno
ENV LDAP_ORGANISATION="Carlos FTP"
ENV LDAP_DOMAIN="carlosftp.com"
ENV LDAP_ADMIN_PASSWORD="admin_password"


