FROM debian:bullseye

RUN apt-get update && \
    apt-get install -y vsftpd libpam-mysql mariadb-client && \
    rm -rf /var/lib/apt/lists/*

COPY vsftpd.conf /etc/vsftpd.conf
COPY vsftpd_virtual /etc/pam.d/vsftpd_virtual

# Usuario ancla para guest_enable
RUN useradd -d /home/ftpuser -s /bin/false ftpuser && \
    echo "ftpuser:ftppass" | chpasswd
RUN mkdir -p /home/ftpuser \
    chown ftpuser:ftpuser /home/ftpuser \
    chmod 755 /home/ftpuser
    
# Creamos única carpeta compartida
RUN mkdir -p /home/ftpusers/ && \
    chown ftpuser:ftpuser /home/ftpusers/ && \
    chmod 775 /home/ftpusers/
RUN mkdir -p /home/ftpusers/shared && \
    chown ftpuser:ftpuser /home/ftpusers/shared && \
    chmod 775 /home/ftpusers/shared
# Directorio para vsftpd
RUN mkdir -p /var/run/vsftpd/empty /var/run/vsftpd && \
    touch /var/run/vsftpd/vsftpd.pid

EXPOSE 20 21 21100-21110

CMD ["/usr/sbin/vsftpd", "/etc/vsftpd.conf"]
