FROM debian:latest

RUN apt update -y && \
    apt install -y nginx 

COPY nginx.conf /etc/nginx/nginx.conf
COPY server.conf /etc/nginx/conf.d/server.conf
COPY fullchain.pem /etc/ssl/certs/fullchain.pem
COPY private.key /etc/ssl/private/private.key

CMD ["nginx", "-g", "daemon off;"]

