---
# 1) StorageClass ya existente para EFS
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc
provisioner: efs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  provisioningMode: efs-ap
  fileSystemId: fs-0dcf013be3156998c
  directoryPerms: "700"

---
# 2) PVC que enlaza al StorageClass de EFS (volumen raíz)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftp-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc
  resources:
    requests:
      storage: 1Gi

---
# 3) Deployment de FTP usando subPath para mapear /ftp del EFS
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      labels:
        app: ftp
    spec:
      containers:
        - name: vsftpd
          image: ftpcarlos
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 21
            - containerPort: 21100
            - containerPort: 21101
          env:
            - name: FTP_USER
              value: "ftpuser"
            - name: FTP_PASS
              value: "ftppass"
            - name: PASV_ENABLE
              value: "YES"
            - name: PASV_MIN_PORT
              value: "21100"
            - name: PASV_MAX_PORT
              value: "21101"
            - name: PASV_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: LOG_STDOUT
              value: "YES"
          volumeMounts:
            - name: ftp-storage
              mountPath: /home/ftpusers/shared
              subPath: ftp    # monta el subdirectorio "ftp" del EFS
      volumes:
        - name: ftp-storage
          persistentVolumeClaim:
            claimName: ftp-pvc

---
# 4) Service de FTP
apiVersion: v1
kind: Service
metadata:
  name: vsftpd
spec:
  selector:
    app: ftp
  ports:
    - name: ftp
      port: 21
      targetPort: 21
    - name: passive1
      port: 21100
      targetPort: 21100
    - name: passive2
      port: 21101
      targetPort: 21101
  type: ClusterIP
