# 2_ftp-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftp-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftp
  template:
    metadata:
      labels:
        app: ftp
    spec:
      containers:
        - name: vsftpd
          image: 799880597301.dkr.ecr.us-east-1.amazonaws.com/imagenes:ftp
          imagePullPolicy: Always
          ports:
            - containerPort: 21
            - containerPort: 21100
            - containerPort: 21101
          env:
            - name: FTP_USER
              value: "ftpuser"
            - name: FTP_PASS
              value: "ftppass"
            - name: PASV_ENABLE
              value: "YES"
            - name: PASV_MIN_PORT
              value: "21100"
            - name: PASV_MAX_PORT
              value: "21101"
            - name: PASV_ADDRESS
              value: "vsftpd"
            - name: LOG_STDOUT
              value: "YES"
          volumeMounts:
            - name: shared-storage
              mountPath: /home/ftpusers/shared
              subPath: ftp
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: vsftpd
spec:
  selector:
    app: ftp
  ports:
    - name: ftp
      port: 21
      targetPort: 21
    - name: passive1
      port: 21100
      targetPort: 21100
    - name: passive2
      port: 21101
      targetPort: 21101
  type: ClusterIP
