---
# 1) PVC para MySQL (se enlaza al PV mysql-pv si lo tienes estático,
#    o bien será provisionado dinámicamente si usas un StorageClass)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-aws
  volumeName: mysql-pv
  resources:
    requests:
      storage: 5Gi

---
# 2) Deployment de MySQL
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 799880597301.dkr.ecr.us-east-1.amazonaws.com/imagenes:mysql
        imagePullPolicy: Always
        ports:
        - containerPort: 3306
        envFrom:
        - secretRef:
            name: mysql-credentials
        volumeMounts:
        - name: mysql-storage
          mountPath: /var/lib/mysql
          subPath: mysql

      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: mysql-pvc

---
# 3) Service para exponer MySQL
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
  - name: mysql
    protocol: TCP
    port: 3306
    targetPort: 3306
  type: ClusterIP
