# mysql-deployment.yaml

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  # Contraseña de root (puedes mover a Secret más adelante)
  MYSQL_ROOT_PASSWORD: "my_passwd"
  # Nombre de la base (debe coincidir con ARG en Dockerfile o sobreescribirse)
  MYSQL_DATABASE:      "mi_basedatos"
  # Datos del admin; ADMIN_PASS no se usa en runtime (solo en build), aquí solo ADMIN_EMAIL
  ADMIN_EMAIL:         "admin@centrodiabullejos.com"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteMany  
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql-carlos:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: mysql-config
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
