# mysql-deployment.yaml (shared EFS)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_ROOT_PASSWORD: "my_passwd"
  MYSQL_DATABASE:      "mi_basedatos"
  ADMIN_EMAIL:         "admin@centrodiabullejos.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      # 1) InitContainer para garantizar que exista /data/mysql en el EFS
      initContainers:
        - name: init-shared-storage
          image: busybox
          command:
            - sh
            - -c
            - |
              mkdir -p /data/mysql
              chmod -R 777 /data/mysql
          volumeMounts:
            - name: shared-storage
              mountPath: /data

      # 2) Contenedor MySQL
      containers:
        - name: mysql
          image: 799880597301.dkr.ecr.us-east-1.amazonaws.com/imagenes:mysql
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: mysql-config
          volumeMounts:
            - name: shared-storage
              mountPath: /var/lib/mysql
              subPath: mysql

      # 3) Volumen compartido
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      targetPort: 3306
  type: ClusterIP
