# mysql-deployment.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_ROOT_PASSWORD: "my_passwd"
  MYSQL_DATABASE:      "mi_basedatos"
  ADMIN_PASS:          "admin"
  ADMIN_EMAIL:         "admin@centrodiabullejos.com"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql-carlos:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: mysql-config
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
