# mysql-deployment.yaml (actualizado)
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  MYSQL_ROOT_PASSWORD: "my_passwd"
  MYSQL_DATABASE:      "mi_basedatos"
  ADMIN_EMAIL:         "admin@centrodiabullejos.com"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-aws
  volumeName: mysql-pv       # ← Aquí vinculamos al PV correcto
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: 799880597301.dkr.ecr.us-east-1.amazonaws.com/imagenes:mysql
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: mysql-config
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
              subPath: mysql
      volumes:
        - name: mysql-data
          persistentVolumeClaim:
            claimName: mysql-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
