---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-aws
provisioner: efs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ftp-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-aws
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d2fb07ea1eb68ec2 # tu FileSystemId
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-aws
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d2fb07ea1eb68ec2
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-aws
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d2fb07ea1eb68ec2
