apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-client
provisioner: example.com/nfs   # lo crea el chart nfs-subdir-external-provisioner
parameters:
  archiveOnDelete: "false"
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
mountOptions:
  - vers=4.1
