apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-aws
provisioner: efs.csi.aws.com
parameters:
  provisioningMode: efs-ap
  fileSystemId:      fs-0c8a0064a653f4fba   # tu FileSystemId
  directoryPerms:    "755"                 # permisos por defecto para nuevos dirs
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy:    Retain
mountOptions:
  - tls


---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: ftp-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-aws
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c8a0064a653f4fba

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-aws
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c8a0064a653f4fba

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-aws
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0c8a0064a653f4fba
