
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carlos-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carlos-web
  template:
    metadata:
      labels:
        app: carlos-web
    spec:
      containers:
        - name: carlos-web
          image: nginx-carlos
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: php-storage
              mountPath: /var/www/html
              subPath: pagina
      volumes:
        - name: php-storage
          persistentVolumeClaim:
            claimName: php-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: carlos-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
