# 4_nginx-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: carlos-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: carlos-web
  template:
    metadata:
      labels:
        app: carlos-web
    spec:
      containers:
        - name: carlos-web
          image: 799880597301.dkr.ecr.us-east-1.amazonaws.com/imagenes:carlos-web
          imagePullPolicy: Always
          ports:
            - containerPort: 80
            - containerPort: 443
          volumeMounts:
            - name: shared-storage
              mountPath: /var/www/html
              subPath: pagina
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: carlos-web
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: https
      protocol: TCP
      port: 443
      targetPort: 443
  type: LoadBalancer
