# 3_php-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
        - name: php-fpm
          image: 799880597301.dkr.ecr.us-east-1.amazonaws.com/imagenes:php-fpm
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          volumeMounts:
            # Código de la web
            - name: shared-storage
              mountPath: /var/www/html
              subPath: pagina
            # Archivos subidos por FTP
            - name: shared-storage
              mountPath: /var/www/html/uploads
              subPath: ftp
      volumes:
        - name: shared-storage
          persistentVolumeClaim:
            claimName: shared-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm-service
spec:
  selector:
    app: php-fpm
  ports:
    - name: php-fpm-port
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
