---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-aws
  volumeName: php-pv        # <--- enlaza al PV php-pv
  resources:
    requests:
      storage: 1Gi

---
# 4) PVC para FTP (subPath "ftp" en EFS)
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ftp-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-aws
  resources:
    requests:
      storage: 1Gi

---
# 5) Deployment de PHP-FPM
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      imagePullSecrets:
        - name: regcred    # si tu imagen es privada
      containers:
        - name: php-fpm
          image: php
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: php-storage
              mountPath: /var/www/html
              subPath: pagina    # monta /mnt/efs/pagina
            - name: ftp-storage
              mountPath: /home/ftpusers/shared
              subPath: ftp       # monta /mnt/efs/ftp
      volumes:
        - name: php-storage
          persistentVolumeClaim:
            claimName: php-pvc
        - name: ftp-storage
          persistentVolumeClaim:
            claimName: ftp-pvc

---
# 6) Service ClusterIP para PHP-FPM
apiVersion: v1
kind: Service
metadata:
  name: php-fpm-service
spec:
  selector:
    app: php-fpm
  ports:
    - name: php-fpm-port
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
