---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: php-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-aws
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d2fb07ea1eb68ec2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs-aws
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      containers:
        - name: php-fpm
          image: 210486000475.dkr.ecr.us-east-1.amazonaws.com/php-fpm:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: php-storage
              mountPath: /var/www/html
      volumes:
        - name: php-storage
          persistentVolumeClaim:
            claimName: php-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm-service
spec:
  selector:
    app: php-fpm
  ports:
    - name: php-fpm-port
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
