---
# 1) PVC para PHP
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs-aws

---
# 2) Deployment de PHP-FPM con initContainer para corregir permisos
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      # Corre como www-data
      securityContext:
        runAsUser: 33
      initContainers:
        - name: fix-perms
          image: busybox:1.35.0
          command:
            - sh
            - -c
            - |
              set -e
              echo "↪ Esperando a que /var/www/html esté montado…"
              for i in $(seq 1 30); do
                if [ -d /var/www/html ]; then
                  echo "  ✅ /var/www/html montado"
                  break
                fi
                sleep 1
              done
              echo "↪ Ajustando dueño y permisos…"
              mkdir -p /var/www/html
              chown -R 33:33 /var/www/html 2>/dev/null || true
              chmod -R 2775 /var/www/html 2>/dev/null || true
              echo "↪ InitContainer completado"
              exit 0
          volumeMounts:
            - name: php-storage
              mountPath: /var/www/html
      containers:
        - name: php-fpm
          image: 799880597301.dkr.ecr.us-east-1.amazonaws.com/imagenes:php-fpm
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: php-storage
              mountPath: /var/www/html
      volumes:
        - name: php-storage
          persistentVolumeClaim:
            claimName: php-pvc

---
# 3) Service para exponer PHP-FPM
apiVersion: v1
kind: Service
metadata:
  name: php-fpm-service
spec:
  selector:
    app: php-fpm
  ports:
    - name: php-fpm-port
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
