apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-aws
  volumeName: php-pv
  resources:
    requests:
      storage: 1Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fpm-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-fpm
  template:
    metadata:
      labels:
        app: php-fpm
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: mysql
          image: 799880597301.dkr.ecr.us-east-1.amazonaws.com/imagenes:php-fpm
          imagePullPolicy: Always
          ports:
            - containerPort: 9000
          volumeMounts:
            - name: php-storage
              mountPath: /var/www/html
              subPath: pagina
            - name: ftp-storage
              mountPath: /home/ftpusers/shared
              subPath: ftp
      volumes:
        - name: php-storage
          persistentVolumeClaim:
            claimName: php-pvc
        - name: ftp-storage
          persistentVolumeClaim:
            claimName: ftp-pvc

---
apiVersion: v1
kind: Service
metadata:
  name: php-fpm-service
spec:
  selector:
    app: php-fpm
  ports:
    - name: php-fpm-port
      protocol: TCP
      port: 9000
      targetPort: 9000
  type: ClusterIP
