---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shared-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-aws
  volumeName: shared-pv
  resources:
    requests:
      storage: 10Gi
