name: Ansible

on:
  push:
    branches:
      - ansible
  workflow_dispatch:

jobs:
  build_and_push:
    name:  Build & Push via Ansible
    runs-on: ubuntu-latest

    steps:
      - name:  Checkout code
        uses: actions/checkout@v4

      - name:  Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name:  Install Ansible & AWS CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          pip3 install --user ansible awscli
          # Aseguramos que los binarios de pip --user estén en el PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name:  Run Ansible playbook
        env:
          AWS_ACCESS_KEY_ID:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_SESSION_TOKEN:     ${{ secrets.AWS_SESSION_TOKEN }}
        run: |
          ansible-playbook ansible/tasks/main.yml -i localhost, --conection=local

