# .github/workflows/deploy-k8s.yaml
name: Deploy Kubernetes Manifests

on:
  push:
    paths:
      - 'kubernetes/**.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            ${{ secrets.AWS_REGION }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: '1.27.0'      # o la versión que prefieras

      - name: Update kubeconfig
        run: |
          aws eks update-kubeconfig \
            --name centrodedia-cluster \
            --region us-east-1

      - name: Apply Kubernetes manifests
        run: |
          kubectl apply -f kubernetes/ 

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/carlos-web-deployment --timeout=2m
          kubectl rollout status deployment/php-fpm-deployment --timeout=2m
          kubectl rollout status deployment/mysql-deployment --timeout=2m
          kubectl rollout status deployment/ftp-server --timeout=2m
