name: Deploy Kubernetes Manifests
on:
  push:
    paths:
      - 'kubernetes/**.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1) Checkout
      - uses: actions/checkout@v4

      # 2) Credenciales AWS para Terraform (backend S3)
      - name: Configure AWS for Terraform
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            us-east-1

      # 3) Instalar Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      # 4) Terraform Init
      - name: Terraform Init
        working-directory: envs/prod
        run: terraform init -input=false

      # 5) Instala kubectl (necesita AWS creds de nuevo)
      - name: Configure AWS for kubectl
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region:            us-east-1

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Update kubeconfig
        run: aws eks update-kubeconfig --name centrodedia-cluster --region us-east-1

      - name: Apply EFS StorageClass & PV
        working-directory: envs/prod
        continue-on-error: true
        run: terraform output -raw efs_storageclass_manifest | kubectl apply --validate=false --server-side -f -











      # 7) Aplica el resto de tus manifests
      - name: Apply other manifests
        run: kubectl apply -f configmap.yml
             kubectl apply -f ftp.yml
             kubectl apply -f ftpsecret.yml
             kubectl apply -f mysql.yml
             kubectl apply -f nginx.yml
             kubectl apply -f php.yml

      # 8) Debug y rollout
      - name: Debug pods & events
        run: |
          kubectl get pods -l app=carlos-web -o wide
          kubectl describe pod -l app=carlos-web
          kubectl logs -l app=carlos-web || true

      - name: Verify rollout
        run: |
          kubectl rollout status deployment/carlos-web-deployment --timeout=5m
          kubectl rollout status deployment/php-fpm-deployment --timeout=3m
          kubectl rollout status deployment/mysql-deployment --timeout=3m
          kubectl rollout status deployment/ftp-server --timeout=3m
