# .github/workflows/deploy-k8s.yaml
name: Deploy Kubernetes Manifests

on:
  push:
    paths:
      - 'kubernetes/**.yaml'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-session-token:     ${{ secrets.AWS_SESSION_TOKEN }}
        aws-region:            us-east-1

    - name: Install kubectl
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/

    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --name centrodedia-cluster --region us-east-1

    - name: Apply Kubernetes manifests
      run: kubectl apply -f kubernetes/nfs-storageclass.yaml
    - name: Apply Kubernetes manifests
      run: kubectl apply -f kubernetes/
    - name: Debug pods & events
      run: |
        kubectl get pods -l app=carlos-web -o wide
        kubectl describe pod -l app=carlos-web
        kubectl logs -l app=carlos-web || true

    - name: Verify rollout
      run: |
        kubectl rollout status deployment/carlos-web-deployment --timeout=5m
        kubectl rollout status deployment/php-fpm-deployment --timeout=3m
        kubectl rollout status deployment/mysql-deployment --timeout=3m
        kubectl rollout status deployment/ftp-server --timeout=3m
